
title: "UCSB Teaching CS"
course: "CS190J"
course_main_url: "https://ucsb-teaching-cs.github.io"
qtr: "M18"
quarter: "Summer 2018"
ta_list: ""
ta_list_full: ""
instructor: "Conrad"

github_url: https://github.com/ucsb-cs190j-m18/ucsb-cs190j-m18.github.io
course_site: https://ucsb-cs190j-m18.github.io

start_week: 1
start_date: 2018-08-05 00:00:00.00-8:00
num_weeks: 6
extra_exam_week: false
sections: "9:30am&nbsp;or&nbsp;11am"

cal_dates: >
  [
  {"label":"Session B classes begin", "date":"2018-08-06" },
  {"label":"Session B classes end", "date":"2018-09-15" },	
  {"label":"Univ Holiday", "date":"2018-09-03" },
  ]



kramdown:
   parse_block_html: true
   default_lang: python

exclude:
   - vendor

timezone: America/Los_Angeles

collections:
  papers:
    output: true
    permalink: /hwk/:path/
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  teams:
    output: true
    permalink: /teams/:path/
  lectures:
    output: true
    permalink: /lectures/:path/



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: teams
    values:
      layout: teams
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


